# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: spanjaan.support::lang.ticketcategory.label

# Model Form Field configuration
form: $/spanjaan/support/models/ticketcategory/fields.yaml

# Model Class name
modelClass: SpAnjaan\Support\Models\TicketCategory

# Default redirect location
defaultRedirect: spanjaan/support/ticketcategories

# Create page
create:
    title: spanjaan.support::lang.ticketcategory.create_title
    redirect: spanjaan/support/ticketcategories/update/:id
    redirectClose: spanjaan/support/ticketcategories

# Update page
update:
    title: spanjaan.support::lang.ticketcategory.update_title
    redirect: spanjaan/support/ticketcategories
    redirectClose: spanjaan/support/ticketcategories

# Preview page
preview:
    title: spanjaan.support::lang.ticketcategory.preview_title