# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    user:
        label: Assignee
        modelClass: Backend\Models\User
        nameFrom: email
        conditions: user_id in (:filtered)
    category:
        label: Category
        modelClass: SpAnjaan\Support\Models\TicketCategory
        nameFrom: name
        conditions: category_id in (:filtered)
    status:
        label: Status
        modelClass: SpAnjaan\Support\Models\TicketStatus
        nameFrom: name
        conditions: status_id in (:filtered)
    priority:
        label: Priority
        modelClass: SpAnjaan\Support\Models\TicketPriority
        nameFrom: name
        conditions: priority_id in (:filtered)
