# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/spanjaan/support/models/ticketattachment/columns.yaml

# Model Class name
modelClass: SpAnjaan\Support\Models\TicketAttachment

# List Title
title: spanjaan.support::lang.upload.list_title

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 25

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: published_at
    direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
